name: migrate-workflow
description: "Migrate workflows from other platforms (Zapier, Make, HubSpot, etc.) to n8n"
author: "Saif"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/autominator/migrate-workflow"
shared_path: "{project-root}/{bmad_folder}/bmm/workflows/autominator/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Shared resources
helpers: "{shared_path}/n8n-helpers.md"
templates: "{shared_path}/n8n-templates.yaml"
platform_mappings: "{shared_path}/platform-mappings.yaml"

# Variables
variables:
  source_platform: "" # Will be elicited
  workflow_description: "" # Will be elicited
  workflow_file: "" # Will be elicited (optional)
  workflow_content: "" # Will be elicited (optional)
  integrations_used: [] # Will be elicited
  trigger_type: "" # Will be elicited
  complexity: "" # Will be elicited
  save_location: "" # Will be elicited
  workflow_name: "" # Will be elicited
  context7_available: false # Will be checked

default_output_file: "{project-root}/workflows/migrated-workflow-{timestamp}.json"

standalone: true
web_bundle: false
