name: autonomous-epic
description: "Autonomous epic processing - creates and develops all stories in an epic with minimal human intervention"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmgd/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmgd/workflows/4-production/autonomous-epic"
instructions: "{installed_path}/instructions.xml"
progress_file: "{story_dir}/.autonomous-epic-progress.yaml"

# Variables
epic_num: "" # User provides or auto-discover next epic
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

# Autonomous mode settings
autonomous_settings:
  use_super_dev: true # Use super-dev-story vs dev-story
  auto_accept_gap_analysis: true # Auto-approve gap analysis refinements
  halt_on_error: false # Continue even if story fails
  max_retry_per_story: 2 # Retry failed stories
  create_git_commits: true # Commit after each story
  git_branch_prefix: "auto-epic-" # Branch name format: auto-epic-{epic_num}

standalone: true

web_bundle: false
