name: super-dev-pipeline
description: "Complete a-k workflow: test-first development, smart gap analysis, quality gates, intelligent multi-agent review, and mandatory status updates. Risk-based complexity routing with variable agent counts."
author: "BMad"
version: "1.5.0" # Complete a-k workflow with TDD, quality gates, multi-agent review, and mandatory sprint-status updates

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{config_source}:sprint_artifacts"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/super-dev-pipeline"
steps_path: "{installed_path}/steps"
templates_path: "{installed_path}/templates"
checklists_path: "{installed_path}/checklists"

# State management
state_file: "{sprint_artifacts}/super-dev-state-{{story_id}}.yaml"
audit_trail: "{sprint_artifacts}/audit-super-dev-{{story_id}}-{{date}}.yaml"

# Auto-create story settings (NEW v1.4.0)
# When story is missing or lacks proper context, auto-invoke /create-story-with-gap-analysis
auto_create_story:
  enabled: true # Set to false to revert to old HALT behavior
  create_story_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/create-story-with-gap-analysis"
  triggers:
    - story_not_found # Story file doesn't exist
    - no_tasks # Story exists but has no tasks
    - missing_sections # Story missing required sections (Tasks, Acceptance Criteria)

# Complexity level (passed from batch-super-dev or set manually)
# Controls which pipeline steps to execute
complexity_level: "standard" # micro | standard | complex

# Risk-based complexity routing (UPDATED v1.5.0)
# Complexity determined by RISK level, not task count
# Risk keywords: auth, security, payment, file handling, architecture changes
complexity_routing:
  micro:
    skip_steps: [3, 7, 8, 9] # Skip write-tests, code-review, review-analysis, fix-issues
    description: "Lightweight path for low-risk stories (UI tweaks, text, simple CRUD)"
    multi_agent_count: 2
    examples: ["UI tweaks", "text changes", "simple CRUD", "documentation"]
  standard:
    skip_steps: [] # Full pipeline
    description: "Balanced path for medium-risk stories (APIs, business logic)"
    multi_agent_count: 4
    examples: ["API endpoints", "business logic", "data validation"]
  complex:
    skip_steps: [] # Full pipeline + comprehensive review
    description: "Comprehensive path for high-risk stories (auth, payments, security)"
    multi_agent_count: 6
    examples: ["auth/security", "payments", "file handling", "architecture changes"]
    warn_before_start: true
    suggest_split: true

# Workflow modes
modes:
  interactive:
    description: "Human-in-the-loop with menu navigation between steps"
    checkpoint_on_failure: true
    requires_approval: true
    smart_batching: true # User can approve batching plan
  batch:
    description: "Unattended execution for batch-super-dev"
    checkpoint_on_failure: true
    requires_approval: false
    fail_fast: true
    smart_batching: true # Auto-enabled for efficiency

# Smart batching configuration
smart_batching:
  enabled: true
  detect_patterns: true
  default_to_safe: true # When uncertain, execute individually
  min_batch_size: 3 # Minimum tasks to form a batch
  fallback_on_failure: true # Revert to individual if batch fails

  # Batchable pattern definitions
  batchable_patterns:
    - pattern: "package_installation"
      keywords: ["Add", "package.json", "npm install", "dependency"]
      risk_level: "low"
      validation: "npm install && npm run build"

    - pattern: "module_registration"
      keywords: ["Import", "Module", "app.module", "register"]
      risk_level: "low"
      validation: "tsc --noEmit"

    - pattern: "code_deletion"
      keywords: ["Delete", "Remove", "rm ", "unlink"]
      risk_level: "low"
      validation: "npm test && npm run build"

    - pattern: "import_update"
      keywords: ["Update import", "Change import", "import from"]
      risk_level: "low"
      validation: "npm run build"

  # Non-batchable pattern definitions (always execute individually)
  individual_patterns:
    - pattern: "business_logic"
      keywords: ["circuit breaker", "fallback", "caching for", "strategy"]
      risk_level: "medium"

    - pattern: "security"
      keywords: ["auth", "permission", "security", "encrypt"]
      risk_level: "high"

    - pattern: "data_migration"
      keywords: ["migration", "schema", "ALTER TABLE", "database"]
      risk_level: "high"

# Agent role definitions (loaded once, switched as needed)
agents:
  dev:
    name: "Developer"
    persona: "{project-root}/_bmad/bmm/agents/dev.md"
    description: "Gap analysis, write tests, implementation, validation, review, fixes"
    used_in_steps: [2, 3, 4, 5, 6, 7, 8, 9]
  sm:
    name: "Scrum Master"
    persona: "{project-root}/_bmad/bmm/agents/sm.md"
    description: "Story completion, status updates, sprint-status.yaml management"
    used_in_steps: [10]

# Step file definitions (NEW v1.5.0: 11-step a-k workflow)
steps:
  - step: 1
    file: "{steps_path}/step-01-init.md"
    name: "Init + Validate Story"
    description: "Load, validate, auto-create if needed (a-c)"
    agent: null
    quality_gate: false
    auto_create_story: true

  - step: 2
    file: "{steps_path}/step-02-smart-gap-analysis.md"
    name: "Smart Gap Analysis"
    description: "Gap analysis (skip if just created story) (d)"
    agent: dev
    quality_gate: true
    skip_if_story_just_created: true

  - step: 3
    file: "{steps_path}/step-03-write-tests.md"
    name: "Write Tests (TDD)"
    description: "Write tests before implementation (e)"
    agent: dev
    quality_gate: false
    test_driven: true

  - step: 4
    file: "{steps_path}/step-04-implement.md"
    name: "Implement"
    description: "Run dev-story implementation (f)"
    agent: dev
    quality_gate: true

  - step: 5
    file: "{steps_path}/step-05-post-validation.md"
    name: "Post-Validation"
    description: "Verify work actually implemented (g)"
    agent: dev
    quality_gate: true
    iterative: true

  - step: 6
    file: "{steps_path}/step-06-run-quality-checks.md"
    name: "Quality Checks"
    description: "Tests, type check, linter - fix all (h)"
    agent: dev
    quality_gate: true
    blocking: true
    required_checks:
      - tests_passing
      - type_check_passing
      - lint_passing
      - coverage_threshold

  - step: 7
    file: "{steps_path}/step-07-code-review.md"
    name: "Code Review"
    description: "Multi-agent review with fresh context (i)"
    agent: dev
    quality_gate: true
    requires_fresh_context: true
    multi_agent_review: true
    variable_agent_count: true

  - step: 8
    file: "{steps_path}/step-08-review-analysis.md"
    name: "Review Analysis"
    description: "Analyze findings - reject gold plating (j)"
    agent: dev
    quality_gate: false
    critical_thinking: true

  - step: 9
    file: "{steps_path}/step-09-fix-issues.md"
    name: "Fix Issues"
    description: "Implement MUST FIX and SHOULD FIX items"
    agent: dev
    quality_gate: true

  - step: 10
    file: "{steps_path}/step-10-complete.md"
    name: "Complete + Update Status"
    description: "Mark done, update sprint-status.yaml (k)"
    agent: sm
    quality_gate: true
    mandatory_sprint_status_update: true
    verify_status_update: true

  - step: 11
    file: "{steps_path}/step-11-summary.md"
    name: "Summary"
    description: "Generate comprehensive audit trail"
    agent: null
    quality_gate: false

# Quality gates
quality_gates:
  pre_gap_analysis:
    step: 2
    criteria:
      - "All tasks validated or refined"
      - "No missing context"
      - "Implementation path clear"

  implementation:
    step: 3
    criteria:
      - "All tasks completed"
      - "Tests pass"
      - "Code follows project patterns"

  post_validation:
    step: 4
    criteria:
      - "All completed tasks verified against codebase"
      - "Zero false positives remaining"
      - "Files/functions/tests actually exist"

  code_review:
    step: 5
    criteria:
      - "3-10 specific issues identified"
      - "All issues resolved or documented"
      - "Security review complete"

# Document loading strategies
input_file_patterns:
  story:
    description: "Story file being developed"
    pattern: "{sprint_artifacts}/story-*.md"
    load_strategy: "FULL_LOAD"
    cache: true

  project_context:
    description: "Critical rules and patterns"
    pattern: "**/project-context.md"
    load_strategy: "FULL_LOAD"
    cache: true

standalone: true
