name: dev-story
description: "Execute a story by implementing tasks/subtasks, writing tests, validating, and updating the story file per acceptance criteria"
author: "BMad"

# Agent Compatibility Documentation
# This metadata documents workflow assumptions without enforcing runtime behavior
agent_compatibility:
  intended_for:
    - agent: "bmm/dev"
      reason: "Developer agent with test-driven development expertise and story execution capabilities"
  assumes_agent_context:
    persona_attributes:
      - "Technical implementation skills (coding, testing, debugging)"
      - "Red-green-refactor TDD workflow understanding"
      - "Familiarity with story file format and acceptance criteria"
    critical_actions_expected:
      - "Loads project-context.md for coding standards and patterns"
      - "Understands story file structure (Tasks/Subtasks, AC, Dev Notes, File List)"
    config_dependencies:
      - "BMM module config at {project-root}/_bmad/bmm/config.yaml"
      - "implementation_artifacts path containing story files and sprint-status.yaml"
  not_recommended_for:
    - agent_types: ["PM", "Analyst", "Architect", "UX Designer"]
      reason: "Requires active code implementation and test writing capabilities"
    - agent_types: ["Game Dev (BMGD module)"]
      reason: "Use bmgd/dev-story workflow instead - different config paths and domain context"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

story_file: "" # Explicit story path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

standalone: true

web_bundle: false
