name: "email-design"
description: "Create email marketing templates with responsive design and conversion optimization"
author: "Marketing Ops Module"

config_source: "{project-root}/{bmad_folder}/marketing-ops/config.yaml"
marketing_output_folder: "{marketing_output_path}"
default_output_file: "{marketing_output_folder}/email-design-{{template-name}}-{{date}}.md"

steps:
  - id: design-brief
    agent: "{bmad_folder}/marketing-ops/agents/marketing-designer.md"
    workflow: "{project-root}/{bmad_folder}/marketing-ops/workflows/design-brief/workflow.yaml"

  - id: email-design
    agent: "{bmad_folder}/marketing-ops/agents/marketing-designer.md"
    output_file: "{default_output_file}"
