# Solution Architecture Workflow Configuration
name: solution-architecture
description: "Scale-adaptive solution architecture generation."
author: "BMad"

# Critical variables
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Inputs expected ( check output_folder or ask user if missing)
recommended_inputs:
  - prd
  - gdd
  - spec
  - architecture
  - epics
  - ux_spec

# Input requirements
inputs:
  - name: project_workflow_analysis_path
    description: "Path to bmm-workflow-status.md from plan-project workflow"
    default: "{output_folder}/bmm-workflow-status.md"
    required: true
  - name: project_level
    description: "Project level (0-4) from analysis file"
    type: integer
    required: true

# Output artifacts
outputs:
  - name: architecture.md
    description: "Complete solution architecture document"
    default: "{output_folder}/solution-architecture.md"
  - name: architecture_decisions.md
    description: "Architecture Decision Records (ADRs)"
    default: "{output_folder}/architecture-decisions.md"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/3-solutioning/architecture"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Reference data files
project_types: "{installed_path}/project-types/project-types.csv"

# Default output location
default_output_file: "{output_folder}/solution-architecture.md"

web_bundle:
  name: "solution-architecture"
  description: "Scale-adaptive solution architecture generation with dynamic template sections. Replaces legacy HLA workflow with modern BMAD Core compliance."
  author: "BMad Builder"
  instructions: "bmad/bmm/workflows/3-solutioning/architecture/instructions.md"
  validation: "bmad/bmm/workflows/3-solutioning/architecture/checklist.md"
  tech_spec_workflow: "bmad/bmm/workflows/4-implementation/epic-tech-context/workflow.yaml"
  # Reference data files
  project_types: "bmad/bmm/workflows/3-solutioning/architecture/project-types/project-types.csv"
  # Workflow dependencies
  existing_workflows:
    - workflow_status: "bmad/bmm/workflows/workflow-status/workflow.yaml"
  web_bundle_files:
    - "bmad/bmm/workflows/3-solutioning/architecture/instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/checklist.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/ADR-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/project-types.csv"
    # Instructions files
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/web-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/mobile-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/game-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/backend-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/data-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/cli-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/library-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/desktop-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/embedded-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/extension-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/infrastructure-instructions.md"
    # Template files
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/web-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/mobile-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/game-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/backend-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/data-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/cli-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/library-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/desktop-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/embedded-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/extension-template.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/project-types/infrastructure-template.md"
