# markdownlint-cli2 configuration
# https://github.com/DavidAnson/markdownlint-cli2

ignores:
  - node_modules/**
  - test/fixtures/**
  - CODE_OF_CONDUCT.md
  - _bmad/**
  - _bmad*/**
  - .agent/**
  - .claude/**
  - .roo/**
  - .codex/**
  - .agentvibes/**
  - .kiro/**
  - sample-project/**
  - test-project-install/**
  - z*/**
  - src/modules/wds/workflows/4-ux-design/interactive-prototypes/templates/**
  - src/modules/wds/workflows/5-design-system/operations/**
  - src/modules/wds/docs/examples/WDS-Presentation/**
  - src/modules/wds/docs/learn-wds/course-explainers/*NOTEBOOKLM-PROMPT.md
  - src/modules/wds/docs/method/phase-6-prd-finalization-guide.md
  - src/modules/wds/workflows/4-ux-design/CONCEPTUAL-SPECIFICATIONS.md
  - src/modules/wds/workflows/4-ux-design/page-specification-quality/step-06-final-validation.md

# Rule configuration
config:
  # Disable all rules by default
  default: false

  # Heading levels should increment by one (h1 -> h2 -> h3, not h1 -> h3)
  MD001: true

  # Duplicate sibling headings (same heading text at same level under same parent)
  MD024:
    siblings_only: true

  # Trailing commas in headings (likely typos)
  MD026:
    punctuation: ","

  # Bare URLs - may not render as links in all parsers
  # Should use <url> or [text](url) format
  MD034: true

  # Spaces inside emphasis markers - breaks rendering
  # e.g., "* text *" won't render as emphasis
  MD037: true
