module = "method"
version = "6.13.0-next"
update_source = "github:bmad-code-org/BMAD-METHOD/skills"
knowledge = ["bmad-meta/method-help.md", "bmad-meta/agents-help.md"]

[requires]
bmad = { version = "6.13.0" }

[recommends]
bmad-build = { version = "6.13.0" }
bmad-code-review = { version = "6.13.0" }
bmad-qa-generate-e2e-tests = { version = "6.13.0" }
bmad-retrospective = { version = "6.13.0" }
bmad-sprint-planning = { version = "6.13.0" }
