name: dev-task
description: "Execute a research or implementation task by implementing subtasks, writing tests, validating statistical correctness, and updating the task file per acceptance criteria"
author: "Quant Method"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
task_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-production/dev-task"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

task_file: "" # Explicit task path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
research_status: "{implementation_artifacts}/research-status.yaml"
project_context: "**/project-context.md"

standalone: true

web_bundle: false
