name: revalidate-epic
description: "Batch revalidation of all stories in an epic. Clears checkboxes and re-verifies against codebase with semaphore pattern."
author: "BMad"
version: "1.0.0"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{output_folder}/sprint-artifacts"
sprint_status: "{output_folder}/sprint-status.yaml"

# Input parameters
epic_number: "{epic_number}" # Required: Epic number (e.g., "2" for Epic 2)
fill_gaps: false # Optional: Fill missing items after verification
max_concurrent: 3 # Optional: Max concurrent revalidation agents (default: 3)

# Verification settings (inherited by story revalidations)
verification:
  verify_acceptance_criteria: true
  verify_tasks: true
  verify_definition_of_done: true
  check_for_stubs: true
  require_tests: true

# Gap filling settings
gap_filling:
  max_gaps_per_story: 10 # Safety limit per story
  require_confirmation_first_story: true # Ask on first story, then auto for rest
  run_tests_after_each: true
  commit_strategy: "per_gap" # "per_gap" | "per_story" | "all_at_once"

# Execution settings
execution:
  use_semaphore_pattern: true # Constant concurrency (not batch-and-wait)
  continue_on_failure: true # Keep processing if one story fails
  display_live_progress: true # Show progress updates every 30s

# Output settings
output:
  create_epic_report: true # Generate epic-level summary
  create_story_reports: true # Generate per-story reports
  update_sprint_status: true # Update progress in sprint-status.yaml

standalone: true
