name: "quick-post"
description: "Fast content creation for social media, quick posts, and short-form content"
author: "Content Creator Module"

config_source: "{project-root}/{bmad_folder}/content-creator/config.yaml"
content_output_folder: "{config_source}:content_output_folder"
user_name: "{config_source}:user_name"
writing_style: "{config_source}:default_writing_style"
date: system-generated

installed_path: "{project-root}/{bmad_folder}/content-creator/workflows/quick-post"
instructions: "{installed_path}/instructions.md"

writing_examples: "{project-root}/{bmad_folder}/content-creator/data/writing-examples.md"
default_output_file: "{content_output_folder}/drafts/quick-post-{{date}}.md"

standalone: true
