# Solution Architecture Workflow Configuration
name: solution-architecture
description: "Scale-adaptive solution architecture generation with dynamic template sections. Replaces legacy HLA workflow with modern BMAD Core compliance."
author: "BMad Builder"

# Critical variables
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Input requirements
inputs:
  - name: prd_path
    description: "Path to PRD document"
    default: "{output_folder}/PRD.md"
    required: true
  - name: project_workflow_analysis_path
    description: "Path to bmm-workflow-status.md from plan-project workflow"
    default: "{output_folder}/bmm-workflow-status.md"
    required: true
  - name: project_level
    description: "Project level (0-4) from analysis file"
    type: integer
    required: true

# Output artifacts
outputs:
  - name: architecture_md
    description: "Complete solution architecture document"
    default: "{output_folder}/solution-architecture.md"
  - name: architecture_decisions_md
    description: "Architecture Decision Records (ADRs)"
    default: "{output_folder}/architecture-decisions.md"
  - name: epic_alignment_matrix
    description: "Epic-to-component mapping (from cohesion check)"
  - name: tech_specs
    description: "Per-epic tech spec documents"

# Workflow variables (set during execution)
variables:
  project_type: ""
  architecture_style: ""
  repo_strategy: ""
  template_sections: []

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/3-solutioning"
adr_template: "{installed_path}/ADR-template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Reference data files
project_types: "{installed_path}/project-types/project-types.csv"
templates: "{installed_path}/project-types"

# Default output location
default_output_file: "{output_folder}/solution-architecture.md"

# Additional workflow dependencies
tech_spec_workflow: "{project-root}/bmad/bmm/workflows/3-solutioning/tech-spec/workflow.yaml"

web_bundle:
  name: "solution-architecture"
  description: "Scale-adaptive solution architecture generation with dynamic template sections. Replaces legacy HLA workflow with modern BMAD Core compliance."
  author: "BMad Builder"
  instructions: "bmad/bmm/workflows/3-solutioning/instructions.md"
  validation: "bmad/bmm/workflows/3-solutioning/checklist.md"
  tech_spec_workflow: "bmad/bmm/workflows/3-solutioning/tech-spec/workflow.yaml"
  # Reference data files
  project_types: "bmad/bmm/workflows/3-solutioning/project-types/project-types.csv"
  web_bundle_files:
    - "bmad/bmm/workflows/3-solutioning/instructions.md"
    - "bmad/bmm/workflows/3-solutioning/checklist.md"
    - "bmad/bmm/workflows/3-solutioning/ADR-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/project-types.csv"
    # Instructions files
    - "bmad/bmm/workflows/3-solutioning/project-types/web-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/mobile-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/game-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/backend-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/data-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/cli-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/library-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/desktop-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/embedded-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/extension-instructions.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/infrastructure-instructions.md"
    # Template files
    - "bmad/bmm/workflows/3-solutioning/project-types/web-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/mobile-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/game-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/backend-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/data-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/cli-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/library-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/desktop-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/embedded-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/extension-template.md"
    - "bmad/bmm/workflows/3-solutioning/project-types/infrastructure-template.md"
