name: autonomous-epic
description: "Autonomous epic processing - creates and develops all stories in an epic with minimal human intervention"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/autonomous-epic"
instructions: "{installed_path}/instructions.xml"
progress_file: "{story_dir}/.autonomous-epic-progress.yaml"

# Variables
epic_num: "" # User provides or auto-discover next epic
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

# Autonomous mode settings
autonomous_settings:
  use_super_dev: true # Use super-dev-story vs dev-story
  auto_accept_gap_analysis: true # Auto-approve gap analysis refinements
  halt_on_error: false # Continue even if story fails
  max_retry_per_story: 2 # Retry failed stories
  create_git_commits: true # Commit after each story
  create_epic_branch: false # When false, stay on current branch (good for parallel epics)
  git_branch_prefix: "auto-epic-" # Branch name format: auto-epic-{epic_num} (only used if create_epic_branch=true)

# TASK-BASED COMPLETION SETTINGS (NEW)
# These settings ensure stories are truly complete, not just marked as such
completion_verification:
  # Use task-based completion instead of status-based
  # A story is ONLY complete when it has ZERO unchecked tasks (- [ ])
  task_based_completion: true

  # Include stories in "review" status if they have unchecked tasks
  # This catches code review findings that were added but not implemented
  process_review_with_unchecked: true

  # Include stories in "done" status if they have unchecked tasks
  # This catches stories incorrectly marked done
  process_done_with_unchecked: true

  # Verify completion after each story by re-scanning for unchecked tasks
  verify_after_development: true

  # Only mark epic as "done" if ALL stories have ZERO unchecked tasks
  strict_epic_completion: true

standalone: true

web_bundle: false
