name: optimize-workflow
description: "Review and improve existing n8n workflows for performance and best practices"
author: "Saif"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/autominator/workflows/optimize-workflow"
shared_path: "{project-root}/{bmad_folder}/autominator/workflows/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Shared resources
helpers: "{shared_path}/n8n-helpers.md"
templates: "{shared_path}/n8n-templates.yaml"
platform_mappings: "{shared_path}/platform-mappings.yaml"

# Variables
variables:
  workflow_file: "" # Will be elicited
  optimization_focus: [] # Will be elicited
  issues_found: [] # Will be identified
  recommendations: [] # Will be generated
  apply_changes: false # Will be elicited
  backup_created: false # Will be set
  context7_available: false # Will be checked

default_output_file: "" # Will use existing file location

standalone: true
web_bundle: false
