# <!-- Powered by BMAD™ Core -->
name: bmad-technical-writing
version: 0.2.6
short-title: Technical Book Writing Studio
description: >-
  Comprehensive AI-powered technical writing framework for technical book
  authors, technical trainers, and documentation specialists. Provides 6
  specialized agents, 8 core workflows with section-driven development (BMad story
  analog), and professional quality assurance tools for planning, writing,
  reviewing, and publishing technical books with code examples, tutorials, and
  learning objectives. Includes 15 checklists for technical accuracy, security,
  performance, publisher compliance, and accessibility. Section-driven workflows
  enable incremental chapter development (2-5 pages per section) with parallel
  development capabilities. Supports publishers like PacktPub, O'Reilly, Manning,
  and self-publishing platforms.
author: Wes
slashPrefix: bmad-tw
