# <!-- Powered by BMAD™ Core -->
name: bmad-technical-writing
version: 0.2.0
short-title: Technical Book Writing Studio
description: >-
  Comprehensive AI-powered technical writing framework for technical book
  authors, technical trainers, and documentation specialists. Provides 6
  specialized agents, 2 core workflows, and professional quality assurance tools
  for planning, writing, reviewing, and publishing technical books with code
  examples, tutorials, and learning objectives. Includes 15 checklists for
  technical accuracy, security, performance, publisher compliance, and
  accessibility. Supports publishers like PacktPub, O'Reilly, Manning, and
  self-publishing platforms.
author: Wes
slashPrefix: bmad-tw
