name: "research-topic"
description: "Deep research on a topic with trend analysis, data gathering, source validation, and unique angle identification"
author: "ClaudeCode Writer Module"

config_source: "{project-root}/{bmad_folder}/claudecode-writer/config.yaml"
content_output_folder: "{config_source}:content_output_folder"
user_name: "{config_source}:user_name"
date: system-generated

installed_path: "{project-root}/{bmad_folder}/claudecode-writer/workflows/research-topic"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

research_sources: "{project-root}/{bmad_folder}/claudecode-writer/data/research-sources.md"
default_output_file: "{content_output_folder}/research/research-{{topic-slug}}-{{date}}.md"

standalone: true
