name: "brand-analysis"
description: "Comprehensive brand analysis including positioning assessment, competitive mapping, and audience perception"
author: "Marketing Ops Module"

config_source: "{project-root}/{bmad_folder}/marketing-ops/config.yaml"
marketing_output_folder: "{marketing_output_path}"
default_output_file: "{marketing_output_folder}/brand-analysis-{{brand-name}}-{{date}}.md"

steps:
  - id: competitive-research
    agent: "{bmad_folder}/marketing-ops/agents/brand-marketer.md"
    task: "{project-root}/{bmad_folder}/marketing-ops/tasks/competitive-research.xml"

  - id: brand-audit
    agent: "{bmad_folder}/marketing-ops/agents/brand-marketer.md"
    task: "{project-root}/{bmad_folder}/marketing-ops/tasks/brand-audit.xml"

  - id: analyze-and-document
    agent: "{bmad_folder}/marketing-ops/agents/brand-marketer.md"
    output_file: "{default_output_file}"
