/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'index',

    // ==========================================
    // DIATAXIS STRUCTURE (Autogenerated)
    // Just drop files in folders - sidebar updates automatically
    // Use _category_.json in folders to control labels/order
    // Use sidebar_position in frontmatter to order files
    // ==========================================
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: true,
      link: { type: 'doc', id: 'how-to/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: true,
      link: { type: 'doc', id: 'explanation/index' },
      items: [{ type: 'autogenerated', dirName: 'explanation' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/index' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

export default sidebars;
