/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'index',

    // ==========================================
    // DIATAXIS STRUCTURE (Autogenerated)
    // Just drop files in folders - sidebar updates automatically
    // Use _category_.json in folders to control labels/order
    // Use sidebar_position in frontmatter to order files
    // ==========================================
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: { type: 'doc', id: 'tutorials/index' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: false,
      link: { type: 'doc', id: 'how-to/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: false,
      link: { type: 'doc', id: 'explanation/index' },
      items: [{ type: 'autogenerated', dirName: 'explanation' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: { type: 'doc', id: 'reference/index' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },

    // ==========================================
    // LEGACY STRUCTURE (Being Migrated)
    // Remove sections as they become empty
    // ==========================================
    {
      type: 'html',
      value:
        '<div style="margin: 2rem 0 0.75rem; padding-top: 1rem; border-top: 1px solid var(--ifm-color-emphasis-200);"><span style="font-size: 0.6875rem; color: var(--ifm-color-emphasis-500); text-transform: uppercase; letter-spacing: 0.05em; padding-left: 0.75rem;">Legacy to be migrated</span></div>',
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'bmad-core-concepts' }],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'modules' }],
    },
  ],
};

export default sidebars;
