name: create-workflow
description: "Create new n8n workflow from scratch based on requirements"
author: "Saif"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/n8n-expert/create-workflow"
shared_path: "{project-root}/{bmad_folder}/bmm/workflows/n8n-expert/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Shared resources
helpers: "{shared_path}/n8n-helpers.md"
templates: "{shared_path}/n8n-templates.yaml"
platform_mappings: "{shared_path}/platform-mappings.yaml"

# Variables
variables:
  workflow_type: "" # Will be elicited
  trigger_type: "" # Will be elicited
  integrations: [] # Will be elicited
  complexity: "" # Will be elicited
  error_handling: "" # Will be elicited
  save_location: "" # Will be elicited
  workflow_name: "" # Will be elicited
  additional_requirements: "" # Will be elicited
  context7_available: false # Will be checked

default_output_file: "{project-root}/workflows/workflow-{timestamp}.json"

standalone: true
web_bundle: false
